name: MultiChatSpigot
version: 1.8
author: Revilo410
main: xyz.olivermartin.multichat.spigotbridge.MultiChatSpigot
softdepend: [Vault,PlaceholderAPI]
commands:
   nick:
      description: Gives a player a nickname
      usage: /nick [player] <nickname / off>
      permission: multichatspigot.nick.self
      permission-message: You do not have permission (multichatspigot.nick.self / multichatspigot.nick.others)
   realname:
      description: Gets the real name of a player from a nickname
      usage: /realname <nickname>
      permission: multichatspigot.realname
      permission-message: You do not have permission (multichatspigot.realname)
   username:
      description: Searches for a user with the specified name
      usage: /username <query>
      permission: multichatspigot.username
      permission-message: You do not have permission (multichatspigot.username)
   multichatspigot:
      description: MultiChatSpigot reload and migrate commands
      usage: /multichatspigot [reload/migratetosql]
      permission: multichatspigot.reload
      permission-message: You do not have permission (multichatspigot.reload)
