name: MultiChatSpigot
version: 1.7
author: Revilo410
main: xyz.olivermartin.multichat.spigotbridge.MultiChatSpigot
softdepend: [Vault,PlaceholderAPI]
api-version: 1.13
commands:
   nick:
      description: Gives a player a nickname
      usage: /nick [player] <nickname / off>
      permission: multichatspigot.nick.self
      permission-message: You do not have permission (multichatspigot.nick.self / multichatspigot.nick.others)
   realname:
      description: Gets the real name of a player from a nickname
      usage: /realname <nickname>
      permission: multichatspigot.realname
      permission-message: You do not have permission (multichatspigot.realname)
   multichatspigot:
      description: MultiChatSpigot reload command
      usage: /multichatspigot reload
      permission: multichatspigot.reload
      permission-message: You do not have permission (multichatspigot.reload)
